apiVersion: v1
kind: Namespace
metadata:
  name: edge-production
  labels:
    name: edge-production
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: edge-staging
  labels:
    name: edge-staging
    environment: staging
